version: '3'

services:
  postgres:
    image: postgres:latest
    ports:
      - "9900:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chelly
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
